name: VillagerShopUI
version: ${project.version}
main: com.alttd.VillagerUI
api-version: 1.19
depend:
  - Vault
  - DataLockLib
author: Teriuihi
commands:
  villagerui:
    permission: villagerui.use
    description: Handles all villagerui commands
    usage: /villagerui